version: '3'

services: 

  nginx:
    restart: always
    container_name: nginx
    build:
        context: ./nginx
    ports:
        - "8080:80"
    networks: 
      - node-network

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db
    command: ['node', 'index.js']

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

    
networks: 
  node-network:
    driver: bridge      

volumes: 
  mysql:
  node_modules: